name: Update MTA Alerts

on:
  schedule:
    - cron: '0 10 * * *'  # Runs at 10:00 UTC, 5:00 EST daily
  workflow_dispatch:       # Allows manual trigger

jobs:
  update-alerts:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install
        
      - name: Fetch and process MTA alerts
        env:
          MTA_API_KEY: ${{ secrets.MTA_API_KEY }}
        run: node src/fetch_alerts.js
        
      - name: Generate HTML
        run: node src/generate_html.js
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          keep_files: true
