name: Update MTA Alerts

on:
  schedule:
    - cron: '0 13 * * *'  # Runs at 13:00 UTC daily
  workflow_dispatch:       # Allows manual trigger for testing

jobs:
  update-alerts:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # We need the previous commit to compare changes
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: |
          npm init -y
          npm install node-fetch
      
      - name: Create data directory
        run: mkdir -p data
      
      - name: Run alert check
        run: node src/fetch_alerts.js
      
      - name: Commit and push if there are changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Check if there are changes to commit
          if git diff --quiet index.html data/last_check.json; then
            echo "No changes to commit"
            exit 0
          fi
          
          git add index.html data/last_check.json
          git commit -m "Update alerts $(date +'%Y-%m-%d %H:%M:%S')"
          git push
